
// ------------------------------------------------------------------
// ENUMS & CONSTANTS
// ------------------------------------------------------------------

export enum UserMode {
  WARRIOR = 'WARRIOR',
  BEAST = 'BEAST',
  LEGEND = 'LEGEND'
}

export enum ArchetypeId {
  WARRIOR = 'WARRIOR_DISCIPLINED',
  BEAST = 'BEAST_UNSTOPPABLE',
  STRATEGIST = 'STRATEGIST_MENTAL',
  SOCIAL_ALPHA = 'SOCIAL_ALPHA',
  MONSTER_BUILDING = 'MONSTER_BUILDING'
}

export enum CardRarity {
  COMMON = 'COMMON',
  RARE = 'RARE',
  EPIC = 'EPIC',
  LEGENDARY = 'LEGENDARY',
  MYTHIC = 'MYTHIC' // "Divine" / "Monster Souls"
}

export enum CardType {
  HABIT = 'HABIT',
  TASK = 'TASK',
  CHALLENGE = 'CHALLENGE', // Social/Physical Challenge
  RITUAL = 'RITUAL', // Peak State, etc.
  IDENTITY = 'IDENTITY', // e.g., "I am a disciplined man"
  SHADOW = 'SHADOW', // Generated by Auto-forgiveness detection
  BOSS = 'BOSS' // Boss fight mechanic
}

export enum ArenaTier {
  CIVILIAN = 0,
  WARRIOR = 1,
  ELITE = 2,
  BEAST = 3,
  LEGENDARY_MONSTER = 4
}

export enum ChestType {
  COMMON = 'COMMON',
  RARE = 'RARE',
  EPIC = 'EPIC',
  LEGENDARY = 'LEGENDARY',
  BEAST = 'BEAST', // 24h exclusive
  DIVINE = 'DIVINE' // 48h exclusive
}

// ------------------------------------------------------------------
// FIRESTORE COLLECTIONS SCHEMA
// ------------------------------------------------------------------

export interface UserProfile {
  uid: string;
  displayName: string;
  email: string;
  avatarId: ArchetypeId; // "Energetic Archetype" ID
  mode: UserMode;
  level: number;
  xp: number;
  trophies: number;
  currentArenaId: string;
  
  // Resources
  gold: number;
  gems: number;
  fragments: number;
  monsterSouls: number;
  
  // Stats
  streakDays: number;
  highestStreak: number;
  battlesWon: number;
  battlesLost: number;
  
  // Meta-data from Assessment
  playerProfile: PlayerAssessmentProfile | null;
  
  createdAt: string; // ISO Date
  lastActive: string; // ISO Date
}

export interface AssessmentQuestion {
  id: string;
  text: string;
  options: string[];
}

export interface PlayerAssessmentProfile {
  primaryGoal: string; // The "90 Day Mission"
  subGoals: string[];
  lifeAreas: Record<string, number>; // Health: 80%, Business: 50%
  quizAnswers: Record<string, string>; // Question text -> Answer text
  
  // AI Generated / Calibrated
  calibrationScore?: number; // Reaction test score
  disciplineLevel: number; // 1-10
  emotionalStyle: string; // e.g., "Strategist", "Emotional"
  topDistraction: string;
  mentalStrength: 'LOW' | 'MEDIUM' | 'HIGH' | 'UNBREAKABLE';
  recommendedMode: UserMode;
  coachPreference: 'ROBBINS' | 'GROVER' | 'CARISMA' | 'BALANCED';
}

export interface BlueprintPhase {
  phaseName: string;
  duration: string;
  focus: string;
  keyHabit: string;
}

export interface AIBlueprint {
  missionStatement: string;
  phases: BlueprintPhase[];
  dailyRitual: string;
}

export interface Card {
  id: string;
  title: string;
  description: string;
  type: CardType;
  rarity: CardRarity;
  energyCost: number; // Mental/Physical energy estimate
  xpReward: number;
  trophyReward: number;
  durationMinutes: number;
  
  // Logic
  isCompleted: boolean;
  completedAt?: string;
  
  // Visuals
  iconId?: string; // For UI
  animationId?: string; // "shake", "glow"
}

export interface Deck {
  id: string; // Usually YYYY-MM-DD
  userId: string;
  cards: Card[];
  
  // Status
  status: 'PENDING' | 'ACTIVE' | 'VICTORY' | 'DEFEAT';
  pressureLevel: number; // 0-100% based on time of day
  
  // AI Context
  aiGenerationNotes?: string; // Why the AI chose these cards
  dailyMotto?: string; // e.g. "Today your mission is sacred"
}

export interface BattleState {
  isActive: boolean;
  currentHp: number;
  maxHp: number; // Represents "Willpower" for the day
  timeRemaining: number; // Seconds until "Day End" or "Sudden Death"
  cardsRemaining: number;
  activeCardId: string | null;
}

export interface Chest {
  id: string;
  type: ChestType;
  status: 'LOCKED' | 'UNLOCKING' | 'READY' | 'OPENED';
  unlockTimeStart?: string;
  unlockTimeEnd?: string; // calculated based on type
  contents?: {
    gold: number;
    gems: number;
    fragments?: number;
    cards?: string[]; // IDs of cards unlocked
  };
}

export interface CoachMessage {
  id: string;
  text: string;
  sender: 'COACH' | 'USER' | 'SYSTEM';
  tone: 'AGGRESSIVE' | 'EMPATHETIC' | 'STOIC' | 'HYPE';
  timestamp: string;
  audioUrl?: string; // Generated by AI TTS
}

export interface AppState {
  user: UserProfile | null;
  currentDeck: Deck | null;
  battle: BattleState;
  chests: Chest[];
  activeScreen: string;
  isLoading: boolean;
  // Temporary state for onboarding
  onboardingData: Partial<PlayerAssessmentProfile>;
  assessmentQuestions: AssessmentQuestion[];
  generatedBlueprint: AIBlueprint | null;
}
